apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sample-mcp-route
  namespace: mcp
spec:
  parentRefs:
    - name: agentgateway
  rules:
    - backendRefs:
        - name: sample-mcp-backend
          group: gateway.kgateway.dev
          kind: Backend
